config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    # path('core/', include('django.contrib.auth.urls')),
    # path('accounts/profile/', ),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import signup, first, task


app_name = 'core'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True)),
    # path('login/', Login, name='login'),
    path('', first, name='first'),
    path('tasks/', task, name='task'),
    path(r'^tasks/(?P<task_id>\d+)/$', task, name='task'),
    path(r'^tasks/(?P<param>\w+)/$', task, name='task'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


# class User:
#     pass


class Task(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    done = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.title} {self.done}'

core/forms.py
from django import forms
from .models import Task, User

from django.contrib.auth.forms import UserCreationForm


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'email': 'Email',
            'username': 'Username',
            'password1': 'Password1',
            'password2': 'Password2:',
        }

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'title': 'Задача:',
        }


# class DoneForm(forms.ModelForm):
#     class Meta:
#         model = Task
#         filds = ('done',)
#         widgets = {
#             'done': forms.BooleanField(attrs={'class': 'form-control'}),
#         }

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LoginView, LogoutView

from .models import User, Task
from .forms import UserCreationForm, TaskForm


def first(request):
    return render(request, 'first.html')




def signup(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect('/core/')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def task(request, task_id=0, param=None, *args, **kwargs):

    user = request.user
    queryset = Task.objects.filter(user=user)
    task_list = queryset.values('id', 'title', 'done')
    form_task = TaskForm(request.POST)
    if param is not None:
        task_list_dell = Task.objects.filter(user=user, done=True)
        task_list_dell.delete()
        queryset = Task.objects.filter(user=user)
        task_list = queryset.values('id', 'title', 'done')
        return redirect('/core/tasks/')

    if task_id != 0:
        task = Task.objects.get(id=task_id)
        # print(task)
        if task.done is False:
            task.done = True
            task.save()

            return redirect('/core/tasks/')
        else:
            task.done = False
            task.save()
            return redirect('/core/tasks/')

    if request.method == 'GET':
        # print(task_list)
        return render(request, 'task.html', {'tasks': task_list, 'form': TaskForm})
    
    if request.method == 'POST':

        task_list = queryset.values('id', 'title', 'done')
        form_task = TaskForm(request.POST)
        print(task_id)
        if form_task.is_valid():
            # form.save()
            title = form_task.cleaned_data['title']
            user = request.user
            task = Task(title=title, user=user)
            task.save()
            task = None
            return render(request, 'task.html', {'tasks': task_list, 'form': TaskForm})
    else:
        form = TaskForm()
        return render(request, 'task.html', {'form': TaskForm})

templates/base.html
<html lang="ru">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <!--Bootstrap css-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
          integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
          crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
          integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
          crossorigin="anonymous"></script>

  <nav class="navbar fixed-top" >
  <ul class=" nav nav-tabs fixed-top scrolling" >

      `
    {% if request.user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'core:task' %}">Мои задания</a>
      </li>
      <li class="nav-item">
            <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>
          </li>
    {% else %}
      <li class="nav-item">
            <a class="nav-link" href="/core/signup/">Регистрация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/core/login/">Login</a>
          </li>
          {% endif %}
  </ul>
  </nav>
</head>
  <br><br>
  {% block content %}
  {% endblock %}
</html>

templates/first.html
{% extends 'base.html' %}

{% block content %}
HELLO



{% endblock %}

templates/signup.html
{% extends 'base.html' %}



{% block content %}

      <div class="row justify-content-end">
    <div class="col-10 text-center">
        <h2><br>Регистрация</h2>
    </div>
<div class="col-md-6">
    <form method="post" class="form">

        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
                {{ form.email.label }}
                {{ form.email }}
            </div>
            <div class="form-group col-md-6">
                {{ form.username.label }}
                {{ form.username }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <i class="white-text active">{{ form.password1.label }}</i>
                {{ form.password1 }}
            </div>
            <div class="form-group col-md-6">
                {{ form.password2.label }}
                {{ form.password2 }}
            </div>
        </div>

        <button class="mt-5 mb-5 align-self-center mt-5 mb-5 btn btn-primary" type="submit">SEND</button>


    </form>
</div>
</div>


  </form>
{% endblock %}

templates/task.html
{% extends 'base.html' %}



{% block content %}


<form method="post" class="form">
        {% csrf_token %}
            <div class="form-group col-md-6">
                {{ form.title.label }}
                <div class="form-inline">
                <p>{{ form.title }}
                    <button class="align-self-center mt-5 mb-5 btn btn-primary" type="submit">New</button>

                    <a href="{% url 'core:task' param='dell' %}" class="btn btn-secondary btn-sm" role="button">Удалить выполненные</a></p>
                </div>
                </div>

</form>


{% for task in tasks %}

    <p>{{ task.title }}
        {% if task.done == False %}
        <a href="{% url 'core:task' task_id=task.id %}" class="btn btn-secondary btn-sm" role="button" >Выполнить</a>
        {% else %}
        <a href="" class="btn btn-secondary btn-sm disabled" role="button" aria-disabled="true">Выполнено</a>
        {% endif %}
    </p><br>

{% endfor %}


{% endblock %}